### ISSUE TITLE
This may already exist

### ISSUE THREAD

**Issue by ghost** [GamearooCodes/AnimeOS#1]
I'm obviously not sure what this operating system would do, but there is an OS called [Daisuki Linux](https://sourceforge.net/projects/daisukilinux/) that claims to be an anime operating system.

I also found [a thread](https://myanimelist.net/forum/?topicid=517909) talking about this which might be interesting to you. 🤷

**Comment by GamearooCodes** [comment]
this is nothing related to what u posted also this is supposed to be a project I'm doing just for fun so

**Comment by ghost** [comment]
alright! well good luck!
